# Generated by Django 4.1 on 2023-01-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='tittle',
            field=models.CharField(max_length=100),
        ),
    ]
