# Generated by Django 4.1 on 2023-01-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_alter_todo_tittle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='tittle',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
